---
- name: Copy a file from Local to Server A
  hosts: all
  tasks:
    - name: Add host to Ansible
      add_host:
        name: 192.168.56.124
    - name: Copy to Server A
      copy:
        src: "{{ local_dump_path }}"
        dest: "/home/{{ ansible_user }}"

- name:
  hosts: all
  vars:
    server_a: 192.168.56.124
    server_b: 192.168.56.125
    db_host:
    db_user:
    db_password:
    db_name:
  tasks:
    - name: Perform PUSH process
      block:
        - name: Add Server B to Ansible hosts
          add_host:
            name: "{{ server_b }}"
        - name: Copy from Server A to Server B
          synchronize:
            src: "/home/{{ ansible_user }}/{{ local_dump_path.split('/')[-1] }}"
            dest: "/home/{{ ansible_user }}"
            mode: push
          delegate_to: "{{ server_a }}"
        - name: Import DB
          shell:
            cmd: "ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ server_b }} 'mysql --force -h {{ db_host }} -u {{ db_user }} --password={{ db_password }} {{ db_name }} < /home/{{ ansible_user }}/{{ local_dump_path.split('/')[-1] }}'"
          delegate_to: "{{ server_a }}"
      always:
        - name: Clean files on Server B
          shell:
            cmd: "ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ server_b }} 'rm -f /home/{{ ansible_user }}/{{ local_dump_path.split('/')[-1] }}'"
          delegate_to: "{{ server_a }}"
        - name: Clean files on Server A
          shell:
            cmd: "rm -f /home/{{ ansible_user }}/{{ local_dump_path.split('/')[-1] }}"
          delegate_to: "{{ server_a }}"
