---
- name:
  hosts: server_a
  vars:
    # SET VALUES FOR ALL THE VARS
    server_a:
    server_b:
    server_b_home: '/home/penn'
    db_host:
    db_user:
    db_password:
    db_name:
  tasks:
    - name: Perform PUSH process
      block:
        - name: Copy to Server A
          copy:
            src: "{{ local_dump_path }}"
            dest: "/home/{{ ansible_user }}"
        - name: Copy from Server A to Server B
          shell:
            cmd: " scp /home/{{ ansible_user }}/{{ local_dump_path.split('/')[-1] }} {{ ansible_user }}@{{ server_b }}:{{ server_b_home }}"
          delegate_to: "{{ server_a }}"
        - name: Check files
          shell:
            cmd: "ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ server_b }} 'ls -la {{ server_b_home }}/{{ local_dump_path.split('/')[-1] }}'"
          register: checkb
          delegate_to: "{{ server_a }}"
        - name:
          debug:
            msg: "{{ checkb.stdout }}"
        - name: Import DB
          shell:
            cmd: "ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ server_b }} 'mysql --force -h {{ db_host }} -u {{ db_user }} --password='{{ db_password }}' {{ db_name }} < {{ server_b_home }}/{{ local_dump_path.split('/')[-1] }}'"
          delegate_to: "{{ server_a }}"
      always:
        - name: Clean files on Server B
          shell:
            cmd: "ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ server_b }} 'rm -f {{ server_b_home }}/{{ local_dump_path.split('/')[-1] }}'"
          delegate_to: "{{ server_a }}"
        - name: Clean files on Server A
          shell:
            cmd: "rm -f /home/{{ ansible_user }}/{{ local_dump_path.split('/')[-1] }}"
          delegate_to: "{{ server_a }}"
